-- ====================================================================
-- SUPABASE SCHEMA SETUP - "TIJERAS LOCAS" BARBERÍA UNIVERSITARIA
-- ====================================================================
-- Ejecuta este script SQL en tu editor de SQL de Supabase para inicializar
-- la tabla 'appointments' con el esquema optimizado y limpio.

-- 1. Crear la tabla de citas (appointments)
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    cliente_nombre TEXT NOT NULL,
    barbero TEXT NOT NULL,
    servicio TEXT NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    estado TEXT NOT NULL DEFAULT 'pending',
    cliente_telefono TEXT NOT NULL,
    cliente_email TEXT NOT NULL,
    total_price NUMERIC NOT NULL
);

-- 2. Habilitar seguridad de nivel de fila (Row Level Security - RLS)
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de Seguridad RLS flexibles para demostración universitaria:
-- Política: Permitir a cualquiera ver las citas (para evitar dobles agendamientos)
CREATE POLICY "Permitir lectura pública de citas" 
ON appointments FOR SELECT 
USING (true);

-- Política: Permitir a cualquiera insertar (cualquier cliente o personal)
CREATE POLICY "Permitir inserción pública de citas" 
ON appointments FOR INSERT 
WITH CHECK (true);

-- Política: Permitir a cualquiera actualizar (para cambios de estado y reprogramaciones)
CREATE POLICY "Permitir actualizaciones públicas de citas" 
ON appointments FOR UPDATE 
USING (true)
WITH CHECK (true);

-- ====================================================================
-- MANUAL DE CONFIGURACIÓN DE USUARIOS DE STAFF (BARBEROS Y ADMIN)
-- ====================================================================
-- Los barberos y administradores NO se registran libremente desde la aplicación.
-- Se crean directamente en tu Panel de Supabase Dashboard:
-- 
-- 1. Ve a Supabase Dashboard -> Authentication -> Users.
-- 2. Haz clic en "Add User" -> "Create User".
-- 3. Ingresa el correo y contraseña deseados.
-- 4. Una vez creado el usuario, haz clic derecho o edita la columna "Metadata"
--    (o "raw_user_meta_data") con el formato JSON correspondiente:
--
--    Para Andrés (DUEÑO / ADMINISTRADOR):
--    {
--      "name": "Andrés",
--      "phone": "+56911112222",
--      "role": "admin"
--    }
--
--    Para Lissy (STAFF BARBERO):
--    {
--      "name": "Lissy",
--      "phone": "+56994151797",
--      "role": "barbero"
--    }
--
--    Para Meylin (STAFF BARBERA):
--    {
--      "name": "Meylin",
--      "phone": "+56971088802",
--      "role": "barbero"
--    }
--
-- Los clientes normales se registran libremente desde la aplicación móvil/web
-- y se les asigna automáticamente el rol de "cliente" por defecto en user_metadata.
-- ====================================================================
