-- ============================================================================
-- PROYECTO: TIJERAS LOCAS - BARBERÍA UNIVERSITARIA & DASHBOARD BI
-- CURSO: Sistemas de Información - Ingeniería Comercial
-- ENTREGABLE: Carpeta /db/tijeras_locas.sql (Scripts DDL y DML)
-- DESCRIPCIÓN: Estructura de base de datos relacional PostgreSQL / Supabase
--              y poblamiento de datos inicial con clientes universitarios
--              y figuras destacadas chilenas y mundiales.
-- ============================================================================

-- ==========================================
-- 1. SECCIÓN DDL (Data Definition Language)
-- ==========================================

-- Eliminar tabla existente para permitir reconstrucción limpia
DROP TABLE IF EXISTS appointments CASCADE;

-- Crear tabla principal de citas (appointments)
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nombre VARCHAR(100) NOT NULL,
    barbero VARCHAR(50) NOT NULL,
    servicio VARCHAR(100) NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'pending',
    client_phone VARCHAR(30) DEFAULT '+56 9 1111 2222',
    cliente_telefono VARCHAR(30) DEFAULT '+56 9 1111 2222',
    client_email VARCHAR(100) DEFAULT 'estudiante@correo.cl',
    cliente_email VARCHAR(100) DEFAULT 'estudiante@correo.cl',
    total_price INT NOT NULL DEFAULT 6500,
    precio INT NOT NULL DEFAULT 6500,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear índices para optimizar consultas de analítica (BI Dashboard)
CREATE INDEX idx_appointments_fecha_hora ON appointments (fecha_hora);
CREATE INDEX idx_appointments_barbero ON appointments (barbero);
CREATE INDEX idx_appointments_estado ON appointments (estado);


-- ==========================================
-- 2. SECCIÓN DML (Data Manipulation Language)
-- ==========================================

-- Poblar la tabla 'appointments' con los datos iniciales de prueba (Seeding)
-- Las fechas se configuran alrededor del Jueves de referenciado (2026-06-11)
INSERT INTO appointments (
    cliente_nombre, 
    barbero, 
    servicio, 
    fecha_hora, 
    estado, 
    client_phone, 
    cliente_telefono, 
    client_email, 
    cliente_email, 
    total_price, 
    precio
) VALUES
-- --- Lunes 2026-06-08 (Pasado) ---
('Álvaro Díaz', 'Andrés', 'Degradado / Fade Humilde', '2026-06-08 11:00:00+00', 'completed', '+5697771122', '+5697771122', 'alvaro@correo.cl', 'alvaro@correo.cl', 8500, 8500),
('Arturo Vidal', 'Meylin', 'Degradado / Fade Humilde', '2026-06-08 10:00:00+00', 'completed', '+56923232323', '+56923232323', 'king@correo.cl', 'king@correo.cl', 8500, 8500),
('Gary Medel', 'Meylin', 'Corte Fade con Diseño + Masaje Capilar VIP', '2026-06-08 11:00:00+00', 'completed', '+56958585858', '+56958585858', 'pitbull@correo.cl', 'pitbull@correo.cl', 11500, 11500),
('Christian Bale', 'Lissy', 'Teñido de Cabello Express', '2026-06-08 15:00:00+00', 'completed', '+56944332211', '+56944332211', 'bale@batman.cl', 'bale@batman.cl', 9000, 9000),

-- --- Martes 2026-06-09 (Pasado) ---
('Johnny Depp', 'Lissy', 'Teñido + Corte Universitario Premium', '2026-06-09 14:00:00+00', 'completed', '+56910101011', '+56910101011', 'johnny.depp@correo.cl', 'johnny.depp@correo.cl', 14000, 14000),
('Felipe Avello', 'Andrés', 'Degradado / Fade Humilde', '2026-06-09 15:00:00+00', 'completed', '+56911227788', '+56911227788', 'avello@pecesito.cl', 'avello@pecesito.cl', 8500, 8500),

-- --- Miércoles 2026-06-10 (Pasado) ---
('Brad Pitt', 'Andrés', 'Corte VIP + Perfilado de Barba Estelar', '2026-06-10 16:00:00+00', 'completed', '+56999912122', '+56999912122', 'brad.pitt@correo.cl', 'brad.pitt@correo.cl', 12500, 12500),
('Charles Aránguiz', 'Andrés', 'Corte VIP + Perfilado de Barba Estelar', '2026-06-10 10:00:00+00', 'completed', '+56920202020', '+56920202020', 'aranguiz@correo.cl', 'aranguiz@correo.cl', 12500, 12500),
('Pedro Ruminot', 'Andrés', 'Corte Clásico Varón', '2026-06-10 13:00:00+00', 'completed', '+56911334455', '+56911334455', 'pedro@correo.cl', 'pedro@correo.cl', 6500, 6500),
('Alexis Sánchez', 'Lissy', 'Degradado / Fade Humilde', '2026-06-10 12:00:00+00', 'completed', '+56999988877', '+56999988877', 'alexis@maravilla.cl', 'alexis@maravilla.cl', 8500, 8500),

-- --- Jueves 2026-06-11 (Día de Referencia / Hoy) ---
('Pedro Pascal', 'Andrés', 'Corte VIP + Perfilado de Barba Estelar', '2026-06-11 13:00:00+00', 'pending', '+56977771234', '+56977771234', 'pedro.pascal@correo.cl', 'pedro.pascal@correo.cl', 12500, 12500),
('Leonardo DiCaprio', 'Lissy', 'Teñido + Corte Universitario Premium', '2026-06-11 17:00:00+00', 'pending', '+56988884321', '+56988884321', 'leo.dicaprio@correo.cl', 'leo.dicaprio@correo.cl', 14000, 14000),
('Keanu Reeves', 'Meylin', 'Corte Fade con Diseño + Masaje Capilar VIP', '2026-06-11 11:00:00+00', 'completed', '+56999991111', '+56999991111', 'keanu@matrix.cl', 'keanu@matrix.cl', 11500, 11500),
('Ben Brereton', 'Andrés', 'Corte VIP + Perfilado de Barba Estelar', '2026-06-11 15:00:00+00', 'pending', '+56933334444', '+56933334444', 'benny@chile.cl', 'benny@chile.cl', 12500, 12500),
('Claudio Bravo', 'Meylin', 'Corte Fade con Diseño + Masaje Capilar VIP', '2026-06-11 19:00:00+00', 'pending', '+56955556666', '+56955556666', 'claudio.bravo@correo.cl', 'claudio.bravo@correo.cl', 11500, 11500),
('Robert Downey Jr.', 'Lissy', 'Teñido + Corte Universitario Premium', '2026-06-11 14:00:00+00', 'pending', '+56934343434', '+56934343434', 'tony.stark@correo.cl', 'tony.stark@correo.cl', 14000, 14000),
('Eduardo Valenzuela', 'Lissy', 'Corte Clásico Varón', '2026-06-11 09:00:00+00', 'completed', '+56988223344', '+56988223344', 'edu.valenzuela@correo.cl', 'edu.valenzuela@correo.cl', 6500, 6500),
('Sebastián Pinilla', 'Lissy', 'Degradado / Fade Humilde', '2026-06-11 10:00:00+00', 'completed', '+56977334455', '+56977334455', 'seba.pini@correo.cl', 'seba.pini@correo.cl', 8500, 8500),
('Javier Toledo', 'Meylin', 'Perfilado de Barba', '2026-06-11 11:00:00+00', 'completed', '+56966442211', '+56966442211', 'javito@correo.cl', 'javito@correo.cl', 5000, 5000),
('Martín Cárcamo', 'Meylin', 'Perfilado de Barba', '2026-06-11 12:00:00+00', 'no-show', '+56955551122', '+56955551122', 'martin@correo.cl', 'martin@correo.cl', 5000, 5000),
('Rodrigo Errázuriz', 'Andrés', 'Degradado / Fade Humilde', '2026-06-11 14:00:00+00', 'pending', '+56911223344', '+56911223344', 'vip.rodrigo@gmail.com', 'vip.rodrigo@gmail.com', 8500, 8500),
('Ignacio Larraín', 'Lissy', 'Degradado / Fade Humilde', '2026-06-11 15:00:00+00', 'pending', '+56944331199', '+56944331199', 'nachol@correo.cl', 'nachol@correo.cl', 8500, 8500),
('Matías Fernández', 'Andrés', 'Teñido de Cabello Express', '2026-06-11 16:00:00+00', 'pending', '+56914141414', '+56914141414', 'matias14@correo.cl', 'matias14@correo.cl', 9000, 9000),
('Gabriel Boric', 'Meylin', 'Perfilado de Barba', '2026-06-11 18:00:00+00', 'pending', '+56922335566', '+5692335566', 'gabriel@presidencia.cl', 'gabriel@presidencia.cl', 5000, 5000);

-- ============================================================================
-- FIN DEL SCRIPT DE BASE DE DATOS `tijeras_locas.sql`
-- ============================================================================
